-- ============================================================
--  Pink Horizon Academy — Default Admin Account
--
--  Creates a special admin record in General_Information
--  (required because UserAccount has a FK to GenID) then
--  creates the UserAccount with Role = 'admin'.
--
--  Default credentials:
--    Username : admin
--    Password : Admin@PHA2026
--
--  The password is stored as a bcrypt hash generated by
--  the Node.js server. Run this script AFTER starting the
--  server at least once (so the DB connection is confirmed),
--  OR just run the app and use POST /api/admin/seed-admin
--  which does this automatically.
--
--  If you want to run it manually here, replace the hash
--  below with a fresh one from: https://bcrypt-generator.com
--  (use 10 rounds, password: Admin@PHA2026)
-- ============================================================

USE PersonINFO;
GO

-- Remove old admin if re-running
DELETE FROM UserAccount           WHERE Username = 'admin';
DELETE FROM General_Information   WHERE StudentNo = 'ADMIN-001';
GO

-- Insert a placeholder General_Information row for the admin
-- (all nullable fields left NULL — admin is not a real student)
INSERT INTO General_Information
    (CampusID, ProgramID, StudentNo, LName, FName)
VALUES
    (1, 1, 'ADMIN-001', 'Administrator', 'Pink Horizon');
GO

-- Create the admin UserAccount
-- Hash below = bcrypt(10 rounds) of "Admin@PHA2026"
DECLARE @adminGenID INT = (SELECT GenID FROM General_Information WHERE StudentNo = 'ADMIN-001');

INSERT INTO UserAccount (GenID, Username, PasswordHash, Role)
VALUES (
    @adminGenID,
    'admin',
    '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',  -- placeholder, overwritten by seed endpoint
    'admin'
);
GO

SELECT ua.UserID, ua.Username, ua.Role, g.FName + ' ' + g.LName AS Name
FROM UserAccount ua
JOIN General_Information g ON g.GenID = ua.GenID
WHERE ua.Role = 'admin';
GO
